runtime: go121

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
#
# This configuration is only used for developer testing. The
# configuration used for development and production instances is
# contained in the infradata/gae repo. Refer to LUCI GAE Automatic
# Deployment for more (http://go/luci/how_to_deploy.md) (Googlers only).
luci_gae_vars:
  luci-tree-status-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    SPANNER_DB: projects/luci-teams-dev/instances/dev/databases/luci-teams-dev

handlers:
- url: /.*
  script: auto
  secure: always

inbound_services:
- warmup

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -spanner-database ${SPANNER_DB}
