runtime: go122
instance_class: F4

# Note: this is interpreted by gae.py, it maps the app ID being deployed to
# values of ${...} vars.
# Reference: https://chromium.googlesource.com/infra/luci/luci-go/+/HEAD/examples/appengine/helloworld_v2/app.yaml
luci_gae_vars:
  luci-bisection-dev:
    AUTH_SERVICE_HOST: chrome-infra-auth-dev.appspot.com
    CONFIG_SERVICE_HOST: config.luci.app
    LUCI_ANALYSIS_PROJECT: luci-analysis-dev
    TINK_AEAD_KEY: sm://tink-aead-primary
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    UI_REDIRECT_URL: luci-milo-dev.appspot.com/ui/bisection
  luci-bisection:
    AUTH_SERVICE_HOST: chrome-infra-auth.appspot.com
    CONFIG_SERVICE_HOST: luci-config.appspot.com
    LUCI_ANALYSIS_PROJECT: luci-analysis
    TINK_AEAD_KEY: sm://tink-aead-primary
    TS_MON_ACCOUNT: app-engine-metric-publishers@prodx-mon-chrome-infra.google.com.iam.gserviceaccount.com
    UI_REDIRECT_URL: ci.chromium.org/ui/bisection

handlers:
- url: /.*
  script: auto
  secure: always

# Pubsub Handler.
- url: /_ah/push-handlers/.*
  script: auto
  secure: always

entrypoint: >
  main
  -auth-service-host ${AUTH_SERVICE_HOST}
  -config-service-host ${CONFIG_SERVICE_HOST}
  -luci-analysis-project ${LUCI_ANALYSIS_PROJECT}
  -primary-tink-aead-key ${TINK_AEAD_KEY}
  -ts-mon-account ${TS_MON_ACCOUNT}
  -ui-redirect-url ${UI_REDIRECT_URL}
